### ISSUE TITLE
Building Docker image fails with no acceptable C compiler found

### ISSUE THREAD

**Issue by danieltrautmann** [GIScience/openelevationservice#23]
I've tried building the Docker image, which failed with the following message. This happens during the step where the Python requirements are installed.

```
configure: error: in `/tmp/pip-build-mmeastyv/gevent/deps/libev':
configure: error: no acceptable C compiler found in $PATH
```

Attached you can find the full log output from the beginning of the step.
I guess this is because the newer Ubuntu Docker images are smaller than before. I'm sure they dropped everything from the image that is not needed.

I'm currently trying to fix this issue and prepare a pull request afterwards.

[docker_build.log](https://github.com/GIScience/openelevationservice/files/4917207/docker_build.log)

**Comment by marcofacheris** [comment]
I had the same issue, I tried with @danieltrautmann 's Dockerfile, and I was able to get past step 2 of the Docker installation guide.

Anyway, I'm now getting this error after launching the command from step 3:

```
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
```

Also, step 4 doesn't look so promising, as mentioned in #25 the link to get FTP credentials is broken, and I'm not even able to reach http://data.cgiar-csi.org/

**Comment by danieltrautmann** [comment]
@marcofacheris Regarding step 3, there might be an issue with your configuration. You may have to adapt the database parameters in [ops_settings.yml](https://github.com/GIScience/openelevationservice/blob/master/ops_settings_docker.sample.yml).

I did this by mounting the file when the container is started via docker-compose.

```yaml
---
version: '3.8'
services:
  postgis:
    image: kartoza/postgis:10.0-2.4
  oes:
    image: YOUR_IMAGE_NAME
    volumes:
      - ./config/ops_settings.yml:/deploy/app/openelevationservice/server/ops_settings.yml
      - ./tiles:/deploy/app/tiles
    ports:
      - "5000:5000"
    depends_on:
      - postgis
```

The issue you have in step 4 are a bit more serious. I can't connect to the website either and I'm pretty sure this is where I downloaded the file. So I don't know how to get them now.
