### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by gurtner-it** [GIScience/openelevationservice#28]
Hi,

I get the following error after: `sudo docker-compose up -d`

```
#0 32.10     copying src/greenlet/platform/switch_x86_unix.h -> build/lib.linux-x86_64-3.6/greenlet/platform
#0 32.10     running build_ext
#0 32.10     building 'greenlet._greenlet' extension
#0 32.10     creating build/temp.linux-x86_64-3.6
#0 32.10     creating build/temp.linux-x86_64-3.6/src
#0 32.10     creating build/temp.linux-x86_64-3.6/src/greenlet
#0 32.10     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/oes_venv/include -I/usr/include/python3.6m -c src/greenlet/greenlet.cpp -o build/temp.linux-x86_64-3.6/src/greenlet/greenlet.o
#0 32.10     unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
#0 32.10     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
#0 32.10     
#0 32.10     ----------------------------------------
#0 32.21 Command "/oes_venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9yrh8slh/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xmv34gcf-record/install-record.txt --single-version-externally-managed --compile --install-headers /oes_venv/include/site/python3.6/greenlet" failed with error code 1 in /tmp/pip-build-9yrh8slh/greenlet/
------
failed to solve: executor failed running [/bin/sh -c /oes_venv/bin/pip3 install -r /deploy/app/requirements.txt]: exit code: 1
(base) beatgurtner@bg openelevationservice % 

```

I did not change the content of the *.yml file:

```
---
attribution: "service by https://openrouteservice.org | data by http://srtm.csi.cgiar.org"
coord_precision: 1e-6
maximum_nodes: 2000
srtm_parameters:
  user: 
  password: 
provider_parameters:
  table_name: oes_cgiar
  db_name: 
  user_name:
  password:
  host: localhost
  port: 5432

```

Should I change  something?

Any idea why I'm getting this error above?

Im using MacOS 13.1 with conda.io, Python 3.11.0 and installed Docker v4.16.2.
